development:
  adapter: postgresql
  encoding: utf8
  database: cien_preguntas_development
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: cien_preguntas_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: cien_preguntas_production
  pool: 5
  username:
  password:

cucumber:
  <<: *TEST
